pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
    stages {
      
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }
        
        stage('Build Image') {
            steps {
                script {
                    sh "docker build -t paseaguau:${BUILD_NUMBER} ."
                }
            }
        }

        stage('Push Image') {
            steps {
              script {
                  sh "docker push paseaguau:${BUILD_NUMBER}"
              }
            }
        }
      
        }
        
    }
} 
